services:
  stats-server:
    build: stat-service/server
    image: server
    container_name: server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - TZ=Europe/Samara
      - PGTZ=Europe/Samara
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=12345

  stats-db:
    image: postgres:16.1
    container_name: postgres-stat
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=dbuser
      - POSTGRES_DB=postgres
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-service:
    build: ewm-service
    image: service
    container_name: service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - TZ=Europe/Samara
      - PGTZ=Europe/Samara
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=12345
      - MY_SERVER_URL=http://server:9090

  ewm-db:
    image: postgres:16.1
    container_name: postgres-ewm
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=dbuser
      - POSTGRES_DB=postgres
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10